development:
  adapter: postgresql
  encoding: unicode
  database: celd
  pool: 5
  username: pdr
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: celt
  pool: 5
  username: pdr
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: celp
  pool: 5
  username: pdr
  password:
